//USER REGISTRATION
export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

//USER LOGIN
export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST';
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL';

//USER LOGOUT
export const USER_LOGOUT_SUCCESS = 'USER_LOGOUT_SUCCESS';

//USER PROFILE
export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_SUCCESS = 'USER_PROFILE_SUCCESS';
export const USER_PROFILE_FAIL = 'USER_PROFILE_FAIL';

//USER UPDATE
export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

// FETCH USERS
export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST';
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
export const FETCH_USERS_FAIL = 'CREATE_USERS_FAIL';

//CARS

export const CREATE_CAR_REQUEST = 'CREATE_CAR_REQUEST';
export const CREATE_CAR_SUCCESS = 'CREATE_CAR_SUCCESS';
export const CREATE_CAR_FAIL = 'CREATE_CAR_FAIL';

// FETCH CARS
export const FETCH_CAR_REQUEST = 'FETCH_CAR_REQUEST';
export const FETCH_CAR_SUCCESS = 'FETCH_CAR_SUCCESS';
export const FETCH_CAR_FAIL = 'CREATE_CAR_FAIL';

//DELETE CARS
export const DELETE_CAR_REQUEST = 'DELETE_CAR_REQUEST';
export const DELETE_CAR_SUCCESS = 'DELETE_CAR_SUCCESS';
export const DELETE_CAR_FAIL = 'DELETE_CAR_FAIL';

//CAR DETAILS
export const CAR_DETAIL_REQUEST = 'CAR_DETAIL_REQUEST';
export const CAR_DETAIL_SUCCESS = 'CAR_DETAIL_SUCCESS';
export const CAR_DETAIL_FAIL = 'CAR_DETAIL_FAIL';

//UPDATE CARS
export const CAR_UPDATE_REQUEST = 'CAR_UPDATE_REQUEST';
export const CAR_UPDATE_SUCCESS = 'CAR_UPDATE_SUCCESS';
export const CAR_UPDATE_FAIL = 'CAR_UPDATE_FAIL';
